"
....``.`..........``````..............`..`.........................................................-
......``............`````..............`````.....................................................---
......`````........-..````.............```.``...........................--......................---:
.......``````.......-..````.............``````..........................--....................-----/
`......```````......-:..````............```````.......................---............-........----:+
```......``````.....:::-..```.............``````.....................--:-...................--.--:/+
````.......``````...-:+:-..```..```.......``.````..................---/+....................---::++o
`````.....`...```....:+/:-...``..```.........`````................--://:....................---/+++o
`````.........````...-/+/:-...`..``.``.........`````.............--:/+:-..................---:/++++/
..````.......-...``...:++/:....`...`````.....-.....`...........--::/++-.``................::///o+-:/
`..`````...`.:-..```..`++++:-..`..```````..../:-....`........----///+o.`.``.............../::/+::./o
`...````.....-:-..``...+///+:--.```````````..-/:-........``.---::/+oo+.````.............:::////..-/o
`.-:-.```.....//:-..``.:/:.+/:--``..```````...:+:-...`......---:/+oo+/.`..........``..../::::::.-:+o
``:/:...``....:/+:-...`.//.-//-:....`..`````.`:+/:---.`....:::/+++oo:-.``......-..```..-///:-...:+oo
``:/+:-..``..../++:-..`.:+:`--:-:-`....``````.-/o//:-.....---/++oooo..```....---..````.:///--..-/ooo
...-+/:-..``...:++/:-.-.-++-...::-...--....```.-o++/:-----:::++ooooo```......---...``.-:/::....-/oo+
....+++:........:o++/:-.:+o:..`-:-....-:-...``.`+o++/----:///ooooo//```...---/:-....`./::--...-/+o++
....+o+/---.`...-++o+/:-:/o/-``.-::....-:-...```/++++::::////oo+oo--`....--/:/:......-/:-.....:+oo::
....-/o+/---...`.:+o++/:::++:.``.-:.....::--..``-+++o/-:///+oooooo--`....--++o/.....-:/-.....-/ooo::
...../o+o/::..``.-+ooo+/::/+/-.``.:-.`..://:-..`./ooo/:////+oooooo.....---:+++/.....-:/-....-:/o++//
`````:+oo+/:-.```./ooo+/:::++/-...--.`..-/+/:...`/ooo::///+oooooo+.....--/+++//:-.`.:::.....:/+o+///
````.:+ooo+::-.``.:+ooo+/::/+o:-..`-.```.:o+/---.:++/////++ooooo+:...-.::++o+//:-.`.:---..--/+oo////
````..:ooo+/::.`.../oooo+/:/+o+/-.`--.```:+o+/:-.-/+:///+ooooooo/:..---//oooo+:-:-..-..---:/+o++////
``....-ooo++::-....:ooooo/::/+++/:....```-/oo//:-://-//++ooooooo/:---:/+oooo+//..:--:..-://+oo+////+
..-...-ooooo/::-`...+ooooo/::+oo+/-.....`.-oo++::-::://++ooooooo+/-:://oooo+/++-.------:/+++oo////++
../.`..+oooo/::-``..-ooooo+/:/ooo+---......ooo++/--///+oooooooo+/////++ooo/::+o/-.--.--/+ooooo////oo
-./...`:+ooo+/::.``.-ooooo++::+oo+/:--`....++oo+/--///+ooooooo++/:://+oooo/:-/o+:.-.--:/+ooo++///+oo
---..-`-+ooo+//:....-/+oooo+/:++ooo+:-..--./+o++:--///+oooooooo+///++ooooo//:+o+:---:-:++ooo++//++oo
yysssssshhhhhhhyysssshhhhhhhhyyhhhhhyyssssssyhhyyyyyhhhddddddhhhyhhhhddhddhyyhhhyysyyyyhddddhyyhhhdd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
