"
`````````.`````````````````````````````````````````````````````````````````````........`````````````
`````````-.``````````````````````..````````````````````````````````````````````........````````````.
``````````...````````````````````````````````````````````````````````````````.......--.``````````...
``````````.-..```````````````````````````````````````````````````````````````.....---.``````````....
``````````-::-.````````````````````````````````````````````````````````````......---..`````````....`
``````````.:/:-..``````````````````````````````````````````````````````````.....--:/..````````....``
```````````.+/:-...````````````````.`````````````````````````````````````......-:://````````.....```
````````````///:....```````````````...```````````````````````````````````.....--:/::```````......```
`.....``````/+++:-...`````.`````````.-.``````````.-.`````````````````````....-::++--``````.......```
``.-...`````./o++:...```````````````-:-..`````````-+.```````````````````....::::oo..`````......`````
``.::-.``````-+++/:-..``````````````-::...`````````:/`````````````````.----://++oo```````......`````
```-/:-..````-/://+:---`````````````.-+:-..````````.+.````````````````.----://oo++`````........`````
````:/::...``.-+--//:-:```````````.``.+/:-..```````:+.```````````````..---::++oo:-````.......```````
````-/+/-...``.+:..:::--.````.````.:.`/++/:-..``.-/+:::::.``````````.--:::++++oo:.```......--``````.
````.:o+::...``+/:`.--::-``````````-:.-+o+:-...``.-:-``.-/-`````````.---//++ooo+--.......---.`````..
`````:+o+/:.--`/o+.`..::-.````...```.-:+o++/:--.````..````.-``````..-:::++ooooo/.:.......::-.`````-:
.````.-oo++:-../+o-``.::-.````.--.`````:oo++/---..```..````.``````.-:///+ooooo/:./-....--/:..`````:/
-.`````++o+/::-:+o/.``.-::.```.-:..````-:o+++:::.-.`-.-``````..```.::///ooooo+--`--...-::/:`..```.:/
--`````:/oo+/:::/++..``.-:.````-/:....`..o++o//:/-..---``````````.-///++ooooo+..`.-----/+o/`...`--//
:-.````-/ooo+/:::/o:-.``.:-.```-//:..````oooo+/:/---.....````````-:///++ooooo/`....::::++/:`.--.--/:
/:-.````-ooo++/:::o+:..`.--.```.-+/:-.```+oooo+/::::-.``..```.``.-://+ooooooo-`....:/+++/:-``::-::--
/::..```-+oooo+/::/++:-.``..````.+++:...`-/ooo++:::::-.`--.`...`-::/++ooooo+/-....-/+++o/..``-::::..
+/::-```.-+oooo+/:/+++:-.`--`````+oo+:-.`-/ooooo/::-::.`::...--.-///ooooooo/-..---:++ooo/.````:/:-..
o+::-...``+oooo+/::/o++/-....````:+oo/:-.:+ooooo//:-.--`.+:..-.-:///ooooooo/-.---:/ooooo/.````-:/:--
oo/::--.``/ooooo+::/+o++/....````./oo+/:-:/+oooo+/::`-:.`++:-..:://+ooooooo++:-:://oooo+:-````-::---
oo//:-.```-/oooo+////oo+/-.-.```.`/oo++/-:/+oooo++::.`...:o/-.:///++ooooooo+/:://++ooo+:...``.----::
oo+/:/.````-ooooo+/::+oo+::--.`.../+ooo+::/+ooooo+/:..`../o+:.:///++ooooooo//-://++ooo+-..````---::/
oo++/:-.```.+ooooo+/:++o++/:-...-:/+oooo///+ooooo++/:-.../+/--:///ooooooooo//::++ooooo+-.````.--::/+
hhhhyyssssssydhhhhhhyhhhhhhyysssyhyydhhhhyyhhhhhhhhyyysssyyyyyyyhydhdddddddyyyyhhdddddhyyssssssyyyyh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
