"
````````````````````````````````````````````````````````````````````````````````````````````........
.`````````````````````````````````````````````````````````````````````````````````````````........--
-..```````````````````````````````````````````````````````````````````````````````````````..........
:-..`````````````````````````````````````````````````````````````````````````````````````.......--``
:/:-.```````````````````````````````````````````````````````````````````````````````````......--:-``
.//:-.``````````````````````````````````````````````````````````````````````````````````....--::+:``
`///:-.``````````````````..``````````````````````.````````````````````````````````````......-://:-``
`/++/:...````````````````...`````````````````````.:.``````````````````````````````````....--::+/-.``
`-:++/:...````````````````.-..````````````````````./-`````````````````````````````````...-:://o:.```
``.o+++:...```````````````-/:-.````````````````````-/```````````````````````````````....--///+o-````
``.+//++:-..```````````````-/:..```````````````````.-``````````````````````````````.---:::/+o++.````
``.//:-+/::-.``````````````.//:-..``````````````--..----.```````````````````````````..---/+oo+/.````
```.//`-:/-:-.``````````````++/:--.``````````````.-.....:/:```````````````````````.-::-:/++oo/:.```.
.```/+.`.:::-:``````````````/+o/::...`````````````-...````-.``````````````````````--:::/++ooo:-````.
..``/+/``.-:::``````.```````-/o+//---....``````````....``````````````````````````.---:+++oooo````...
---`/+o.``.-::..````...``````-o+++:--..---.`````````--..`````````````````````````-///++oooooo````...
/--./+o:.``.-:-.````---```````+oo++:-:.`````````````::-.```````...`````````````..:///ooo+oo::``.`...
+/:-:/o+:```.-::````.-:-.`````:+o++/::-.``````````./://-.```````..`..`````.````:////+oooooo:-.`....-
+/::::+++.```.-:.````-+:..````-/o+o+/:::````````.:/-`++:..``````````.-````.....:///++oooooo/:.....--
oo/:::/+o-.``.-:.````-//:-..```-ooo++:::..`--...-.```:++:-.``````````.````-/-.-:///++oooooo/:....--:
oo+/:::+o/-....--.```.-++/-.```-+oooo//:-.````.``````:++/:-.``````````````.::--://+ooooooo+/:...--/+
ooo+/:://+/--.``-.`````+++:-..`./oooo+/::..```.``````.+:+/:-``:-````.``````-/////++ooooo+/+/:----:/+
oooo+:::/o+/:-.`-.`````+o++::.`.:ooooo+/:-..``..`````.+:.:::.`/:.```..``..`.-////ooooooo+::::--::/++
oooo+/:::o+++:-`...````:+oo/:-.-/+oooo+//:-......```.-/+..-:-``/:.```-..`...-//++ooooooo+::-:-:/++oo
ooooo+/::++o+/:....````.:oo++--::++oooo+/::...`...``-::+/``-:``:+:.``/:-`..-://++oooooooo+/-:::/oooo
:ooooo//:/+oo/:-...`````-ooo+/:-:++oooo+/::...``....:+/+o.``..`-+/--.:/-...////ooooooooo+////:++oooo
-ooooo++::+ooo+:---`````-oooo+/::++ooooo//:-.````...:++/o:.``.`.o+/-.-/:...///+ooooooooo//::/+++oooo
.+ooooo+///+o+++:-:`````.+oooo+/:/+ooooo++/:-..`...-:///o+/.`.``oo+/:-/:-..///+ooooooooo+/::++oooooo
syhhhhhhhyyhhhhhhysssossshhhhhhhyhhhhhhhhhyyssssysssysyyhhhyssosyhhhyyhyysyyyyhhhhhhhhhhhyyyhhhhhddy
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
