"
.....................----...........................................------...................---....
--...................------.....................--...................------........--..........---..
----...................-----.....................--..................------.........--.........----.
----....................-----.....................---................---------......---.........----
------..................-----.....................-----...............-:------.......---........----
.-----.................-::----.....................-----...............//:----.......-----.......---
..---...-..............-:::----..---...............------.............-://:---........-----......---
..---..-.....---.......--/:----....-.....-.........-------.....---....--++/:--.........-----......--
...--------.---.....-...-+//:----.---.....--....--..------......---....-+o+/:--........-----......--
...-------....-....--....///::--....---....----..----------.....----....-+o/::---......------......-
.....::---......----.....-/o+/:--...-----...---..---.:::---.....----....-/o+/:::--......:-----.....-
.....//:---.....----....../oo/::--...----..-----.....-::-----......---..-/ooo/:::-......:::-----....
....-///:---...-----.....-:oo+/::--..-----------...--::/::---......---...:+so++:/:-.....-:/:----....
..----+//----..-:---....--+ooo+//:-.-------::---.-----:++/:----....----..-/sooo//:-....../o/:---....
------///:::---------..---:/ooo+//:-.-::---:---------.-/o+/:---....-----.-/sooo+/::....../oo/::--...
-:-...-/o/::::---:---.-:---:o:+o++/:-.//:-:-..---------:oo+/---.....:-----/ooo++///-.....:/o+/::--..
::-...-/o+/:::---/-----:-.-:o::/++/:-./+/::-..-:----:--:+oo+/:--....:::--::+so+:///:....--/so+/:::-.
:-...../+o+//::--:::--:--..-+o::/++/:-:/o/:--.-:::---::::ooo///-...-://::--/ss+/-://...---:oooo//:--
:-....-:+o+++::::::::::-...-/s/:-:///--/o+/:---:+/:--:::-oooo///:----++/--:/oso+--:+----:--/ooo+//:-
:....---/o+oo:://::::::--..-:so/--://-./oo+/:-:/o//:-/::-ooooo+//::-.+o+::::oooo:-:/----:--:osoo+//:
-...-:--:o+oo+//:--::/:--.--:oo+---::-.:+o++:/-:++/:::/:-+oooo++//:-./+o/:::oooo/---/::-:.-:oooo++//
-.--::-.:/++oo//:-::::::----:+so/------:/soo+/::/o+/::::::ooooo++/:..-+oo//:/oooo:--::::--.-ooooo++/
-.-:::-.-/oooo+//::::--:---::ooo+:---::::sooo/:::oo/::::/:oooooo++:...+oo++//oooo/--:--:.-.-/osooo+/
---::-..-:ooo+o///:::---::-::+ooo+::-::::ssoo+///oo+::::/:+ooooo++:-.-+ooo+/+ooss+:---:-.--.-+sooo+/
--:::-...:ooooo+/////---:::::/oooo+/::::/+oooo+/+oso/--:/:+oooooo+/:--/+so++/ooooo+/:-:-.---:+sooo++
-::::-...:+oo+o+//////---:::::osooo+/::://oooo+++oso+:--://+ooooo++/-:/+sooo/oooooo+/:-..---:+soooo+
-:::-...-:+ooooo+//++o::-:/:::ooooooo+::::osoo+++oooo:---//ooooooo+//::+sooo+ooooooo+/:-.----ooooooo
-:::-...--:+oooo++///o+/::::::ossooooo//::ooooo+++ooo+::::/+oooooo++/::+ooooooossoooo/:-.--:-/+ooooo
yyyyssssyyydhhhhhhhyhhdhyyyyyyhdddddddyhhyhdddhhhhddddhyyyyhhdddddhhhyyhddddhhdddddddhyyssyysyhddddd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

"
