"
........`.............................------...............------::-........-----..........--.......
.......`.............................------..............------:::--.......-----..........---.......
.....```.............................----.................----::/+--......------.........----.......
....```............................------...............-----:/+++-.......------.......-----........
....``.............................------..............----::/+o+/-.....-------........---..........
...`...........`.................-----:--........--...---:::/++o/-.....------........-----.........-
..`...........``................-----::-........-......-::::/+o+:......------.......------.........-
.`..--......``........``........----::--.....----....---:::/ooo+:....----:::-.......------.......---
`..::-.....``........``.......----::/:--....----......::::/oooo.....-----::--.....------.-.......--:
..://-....`.........``........---::/+:.....-----....-.:::++oooo.-..----:///.......--------.....--:::
.-//:....``........``........---:/++/-.`...-----....-:://o+++++...---:::+/:......----:::-......--:::
-/++:.............``........--:://oo:-`..-----......:///+o/:+/:...-:://+o:-...`.-----//--......-/:/+
/++:...`..-:......`........--://++oo..`.------.....-///++:-:o:-.--:://+++-.....---:::+/-......-://+o
///:.....:/--...``.---.....:::/+ooo:``..--------..-/////:-:/s--.-::/+oo+:-..`..--::/oo/.......::++oo
-:/-...-://.......-/-....--///+oos/-`..------:/-..-///:---/+o.--::/++oo/-..`..---:/+o/:.......///ooo
./+...-:++-......-//-....-:/++ooos:...-----:://..-://:----ooo-:///+ooo+:..`..---:/oos--.....-:/+//+o
:+/.--:++/......:/+-...--://+ooooo:.------://+:..:///:..-/ooo::/++oooo:-.`..--:://oo+-......-///::+o
/o/--:+oo-....--/++-...-:///oooso/:-----:://+/-..///----:+o++://+ooooo-..`.-:///+oso+......-///:-/os
++:://oo+....:-/+o/-...-//++oooso:::---:/++/+:.--/::----/oo+//++ooso+/....-:///ooos/-.....--//:--oos
+/::/oo+:...-::+oo:-..-:+++oooooo:::-::/++o++-.-:/::---:+oo+//++ooss+/...-::/++ooos::.....--//-::ooo
+::/+oo+....-:/+o+:...-:/++oooooo::--:/+o++o/---:/::--:+oo++/++oooss:.....://++oooo--..-..-/---:/ooo
/:/+ooo/...-:/ooo/-...//++osooo++/:-::+oo++o/:--/----:/ooo//++ooosoo:....-//+oooooo--.--.--:---/oooo
::/oooo-...::+ooo-...-/++oososo///::/+ooo+++:--::-::/+oo++/++ooooso+-...-//++oooso/-..--.--:--:+oooo
:/+ooo+...-:/+ooo-..-:/++ooooso+/::/+ooooo+/:::::://+ooo++/+oooooso-....-//+ooooso--.-...-----/ssooo
:+ooo+-...-:/+ooo:..://+oooooso++/:+ooso++o/:---::/+oooo++/+ooooos+.--.::+++oooos+--.-...----/osoooo
/+ooo+....:/+ooo/-.-///+ooossoo+///oooso++o/--::://+oooo+++ooooooo/....//+++oooos+:---...--:/+ooooo+
+oooo/...-:/+ooo:.--//+oooossoo+//ooooso+++/..:///+ooso++++ooooss+:...-//++oooooo+----...-:/ooooooo+
+oooo:...:/+oooo:--:/+oosssssoo+++oooooo+++:.-///+ooooo+++oooosss+-.--:+++ooooooo/----.--//+oooooso+
hhhhdssssyyhhhhhyyyyhhhdddddddhhhhdddddhhhhssyhhhdddddhhhhdddddddhssyyyhhhhdddddhyyyyssyyyhhddddddhh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
