"
.....................``............................-----...................-----:///........-------.
................................................--------......``.........------:/++/.......--------.
...................```.........................---------.....``.........-----::/++:-......-------...
..................``..........................----------....```..--.....----:///+o--....---------...
.................``...........................------::-....```..----....--::://+++.....---------....
.......`.........``.........................-------:--....````----....---::::++o++-...-----------...
......`.........``..................`.......------::--...``...-----...--::://ooo++-...-----::::.....
....```........`..---..............``.......----:://--...`..-.--.-....--::/+oooo-....----:-:/--.....
...````..........-/-..............``.......----::///-......-----....---::/+ooooo-..------:///:......
..````..........-:+-.....`......``........----://+/:......-------....:::/+o++/+o-...---::/+/:-....--
..``...........-/+/-....`......```....`...---:://o:-.....-------....-://++o::++/-..---://+o:--....--
.`............-:/+.....``....````.....`..--:://++o:.....--:---.....-:///+/:-/o/------::/+o+:......--
`..---.......-:+++....``.........--..``.-:::///oo+:....--::---.....///++/:-:/s:.----::/+oo/-......--
..-:.......:-:+++:...``.........-:-.``..-:::/+ooo//-.---:::--......////::--++s-.--:::/+ooo--....-.--
.-:/-......::++o+..````........-/:-`...-:///ooos+:-/---:::::..``..-///::--:ooo-./::/+oooo+......---:
-:+:-.....:-/+++/..``.........:/+-....-:::++ooos:..---::::::.-.`.-:///---::soo:-://+oooo/:....--::::
:+o-......::-:+o/.`...-.....-:/++....-://+oooooo:..:-:-::+::---..///::---/+so+:://+ooooo-.....--:///
/o+-.....-:--:oo-...--.....-:/+o:....::/++oooso/-.-----:/+--..-.-//::---:+oo+////+ooooo+......-:///o
+o:-.....:-.-+oo-..-:/....::/+++.--../+++oooooo:-.-::-:++o-....-:/::---::ooo///++ooooo++:-....:///oo
oo--.....:../ooo...:+/`..-:/++++-----/++ooooooo-.--::::oo+.....::/:----//oo++//++oooss+//:..-::/++oo
o+......-..:+o+/.-:/+:...::/+oo/---::/++ooooooo-.--::++o+:-....::/:--::/+oo++/++ooooso::-:---://+ooo
+/........./+o+:.-/++--.-:/+ooo:---///+ooooooo+.---:/ooo+:-....::----:/+oo+//++oooooo+./.---://+oooo
+.``......-+oo+::/+o/::.::/ooo+::-:/++oooooss+:.-::/+ooo+......::---//+oo+++/+oooooso+./:..///++oooo
+..`.....-/+oo+::+o+:-:::/+ooo/--::/++oooosss+/-::/+oooo:...---/:-::+oooo+++++ooooss+:-:/..///ooooos
+.`.....-/+oo++:+oo/---:/+oooo:--://+oooooooo+/::/+oosoo:.-..-:::://ooooo+++++ooooos+:--/--///ooooos
/......:/oooo++/+oo/..-:/+oooo:--///+oooooooo////+oooso/-.-..-::::++ooooo/++oooooooo+/:-:///++ooooss
-...--.:+oooo+/+oo+:.-::+oooo+---//++oooooooo//:+ooooso/:-...::::/+ooooo+/+ooooooo+/++/--://++ooooos
...---:/+ooooo/+oo+:..:/+ooo+/--:/+++oooooooo///oooooso//-.--:////oooss++/+oooooss/:++/:-//+oooooooo
sssyyyyhhhhhddhhhhyssyyhhhhhhyyyyhhhddddddddhhhhddddddhhyyyyyhhyhhdddddhhhhdddddddyshhyyyhhhdddddddh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
